# Generated by Django 3.2.3 on 2023-06-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewerprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='domain',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('accepted', 'rejected')], default='draft', max_length=10),
        ),
    ]
