# Generated by Django 3.2.3 on 2023-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_auto_20230630_0351'),
        ('authentication', '0002_auto_20230629_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerprofile',
            name='domains',
            field=models.ManyToManyField(related_name='domains', to='paper.Domain'),
        ),
        migrations.AlterField(
            model_name='reviewerprofile',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='draft', max_length=10),
        ),
    ]
