# Generated by Django 4.2.2 on 2023-06-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_reviewerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerprofile',
            name='institute',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reviewerprofile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviewerprofile',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
