# Generated by Django 4.2.1 on 2023-05-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='institute',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='mentor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
