# Generated by Django 4.2.1 on 2023-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_paper_authors_paper_institute_paper_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
