# Generated by Django 3.2.3 on 2023-06-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_paper_reviewer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper',
            field=models.FileField(null=True, upload_to='papers'),
        ),
    ]
